### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by strongSoda** [strongSoda/CeramicPortal#1]
Design a **suitable** and **high resolution** logo for our project.

The logo shall follow these guidelines:

- It must be available in web safe formats like JPEG, PNG, SVG etc.
- It must not resemble any existing logo.
- It must be consistent with the color pallete of our webapp.

You can use [this](https://www.tailorbrands.com) resource to design logos. But don't just take any logo it generates as it is. Customise it to make it unique.

Make a number of logos , then we'll vote to select the final one.

**Comment by strongSoda** [comment]
If you have any doubts or want to get suggestions on your logos u can post everything here in this issue itself .  It'll help to keep things sorted and also give you experience of **open source development** . 

If you want to work on this issue all by urself then claim this issue here.

**Comment by ggabogarcia** [comment]
Hello, I'm interested in your request, that's why I designed this proposal, I hope you like it. About the color I would like to know what is the exact number to use it.
# 
![ceramicportal](https://user-images.githubusercontent.com/35750428/46975768-1e2c8380-d08d-11e8-9ac8-7395f6411a04.jpg)

**Comment by strongSoda** [comment]
Thanks! for taking interest in our project @ggabogarcia . I like your proposal. There are few things to note here.

- This project has been named  "Maati" .So the brand name beside logo must be Maati.
- Regarding no. of colors, go with 2.
- And it would be nice to have a couple options in logo.

For your Information:

- The name "Maati" stands for soil/clay with which ceramics are made.
- U are free to either show ceramics or clay in the logo.
- Be as creative as u want in the logo.

**Comment by strongSoda** [comment]
Oops, that was a wrong click!  Issue is open!

**Comment by ggabogarcia** [comment]
Thanks for the information, I will make the changes according to that.

**Comment by ggabogarcia** [comment]
Hello again :smiley: here I present my next proposal. I try to be as minimal as possible, my main base was the soil and its different layers, investigate that the clay is divided into different classes and is present in each of these layers. The design of the isotype is built inside a golden rectangle that gives it a better visual aesthetic. I hope it works.
# 
![maatii2](https://user-images.githubusercontent.com/35750428/47117420-e3138700-d229-11e8-8708-5ef66ac6d416.jpg)

**Comment by strongSoda** [comment]
@ggabogarcia  This one looks amazing :100:  ! 

I would like to finalize this one :heavy_check_mark: . Go ahead and open up a PR. Plz send various sizes of logo like 16x16, 32x32, 64x64 and bigger & other relevant sizes & colors for all aspects of website.

**Comment by ggabogarcia** [comment]
That is incredible, I will proceed to make the different sizes, and I will send editable files, Svg, Png and Eps through a link Gdrive, I would like to see the site when it is incorporated.

**Comment by strongSoda** [comment]
Yea sure @ggabogarcia. Also I'll link ur github profile in the project readme as a citation under the logo.

**Comment by ggabogarcia** [comment]
Hello :1st_place_medal: 
## [Files](https://drive.google.com/drive/folders/1WLxM0c-CL_souZ_TmkYhs8ZDhdtHLXSt?usp=sharing)

![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by strongSoda** [comment]
No inconveniences, Thanks for contributing @ggabogarcia . If there's anything from your side, plz let me know.

**Comment by strongSoda** [comment]
Since this is done, hence closing the issue!
